### ISSUE TITLE
Link to the deployment from the repo

### ISSUE THREAD

**Issue by samestep** [AlexDonley/speak_up#1]
Hey Alex! 😃 Super cool project ya got here, been meaning to look at it for a while but been busy with travel etc 😵‍💫

Super tiny nit, but it'd be convenient if you can add your deployment URL to the repo; if you go to the [main repo page](https://github.com/AlexDonley/speak_up) you should have an edit button under the **About** section in the top-right corner, and if you click that, there should be a checkbox to display your GitHub Pages site. Or you can just type it manually into that box: https://alexdonley.github.io/speak_up

**Comment by AlexDonley** [comment]
Fantastic, thanks for the feedback! Just added it to the About section and I'll do the same for my other projects. Still pretty new to Github so I'm guessing my work is missing a lot of polish -- all pointers are welcome! If you see any other issues feel free to open them.
